# -*- coding: utf-8 -*-
"""contourf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FDNJOAoieHHu1FyXUPZgM8NJkRAl-HXB
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

"""
# contourf(X, Y, Z)

See `~matplotlib.axes.Axes.contourf`.
"""

import matplotlib.pyplot as plt
import numpy as np

#plt.style.use('_mpl-gallery-nogrid')

# make data
X, Y = np.meshgrid(np.linspace(-3, 3, 256), np.linspace(-3, 3, 256))
Z = (1 - X/2 + X**5 + Y**3) * np.exp(-X**2 - Y**2)
levels = np.linspace(Z.min(), Z.max(), 7)

# plot
fig, ax = plt.subplots()

ax.contourf(X, Y, Z, levels=levels)

plt.show()