plt.style.use('classic')
plt.plot(data)
plt.show()

plt.style.use('Solarize_Light2')
plt.plot(data)
plt.show()

plt.style.use('_classic_test_patch')
plt.plot(data)
plt.show()
plt.style.use('dark_background')
plt.plot(data)
plt.show()
plt.style.use('fast')
plt.plot(data)
plt.show()
plt.style.use('fivethirtyeight')
plt.plot(data)
plt.show()
plt.style.use('ggplot')
plt.plot(data)
plt.show()
plt.style.use('grayscale')
plt.plot(data)
plt.show()
plt.style.use('seaborn')
plt.plot(data)
plt.show()

plt.style.use('seaborn-bright')
plt.plot(data)
plt.show()

plt.style.use('seaborn-colorblind')
plt.plot(data)
plt.show()
plt.style.use('seaborn-deep')
plt.plot(data)
plt.show()
