
plt.plot(x,y, '.')
plt.plot(x,y+0.5, ',')
plt.plot(x,y+1, 'o')
plt.plot(x,y+2, '<')
plt.plot(x,y+3, '>')
plt.plot(x,y+4, 'v')
plt.plot(x,y+5, '^')
plt.plot(x,y+6, '1')
plt.plot(x,y+7, '2')
plt.plot(x,y+8, '3')
plt.plot(x,y+9, '4')
plt.plot(x,y+10, 's')
plt.plot(x,y+11, 'p')
plt.plot(x,y+12, '*')
plt.plot(x,y+13, 'h')
plt.plot(x,y+14, 'H')
plt.plot(x,y+15, '+')
plt.plot(x,y+16, 'D')
plt.plot(x,y+17, 'd')
plt.plot(x,y+18, '|')
plt.plot(x,y+19, '_')
plt.show()
